version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: helloworld
      POSTGRES_DB: golearn
    ports:
       - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 3333:8080